[versions]
detekt = "1.23.8"
kotlin = "2.2.21"
ktlintGradle = "14.0.1"
pluginPublish = "1.3.1"
versionCheck = "0.53.0"
docker-client = "3.7.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck" }
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
plantuml = { id = "io.gitlab.plunts.plantuml", version = "2.3.0" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
git = { id = "com.xenoterracide.gradle.git", version = "0.14.2" }
manifest = { id = "com.coditory.manifest", version = "1.1.0" }

[libraries]
junit = "junit:junit:4.13.2"
docker-java-core = { group = "com.github.docker-java", name = "docker-java-core", version.ref = "docker-client" }
docker-java-transport-httpclient5 = { group = "com.github.docker-java", name = "docker-java-transport-httpclient5", version.ref = "docker-client" }
apache-common-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }
